### ISSUE TITLE
UI/UX: Enhance light/dark mode

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/scaffold-stark-2#116]
## Issue Overview

the label for `Multiply by 10^18 (wei)` working well on light mode 
![image](https://github.com/Quantum3-Labs/scaffold-stark-2/assets/22782504/5c87f0a0-bb5f-4848-a846-b1913aae4109)

But not working well on dark mode
![image](https://github.com/Quantum3-Labs/scaffold-stark-2/assets/22782504/01937e73-530e-49ca-90d7-34d6ac62cb6a)

## Proposed Solutions or Ideas

- Adjust font color

**Comment by GabrielaDelPilarR** [comment]
fix font color in  challenge-base branch 
<img width="310" alt="Captura de Pantalla 2024-05-06 a la(s) 23 08 09" src="https://github.com/Quantum3-Labs/scaffold-stark-2/assets/77763655/b0effb29-183a-4231-87b2-926f1e0d10be">
<img width="324" alt="Captura de Pantalla 2024-05-06 a la(s) 23 08 15" src="https://github.com/Quantum3-Labs/scaffold-stark-2/assets/77763655/7db6df01-f078-4f95-a743-63d96e3f63e4">
