### ISSUE TITLE
Arrow to display more info incorrect positioned 

### ISSUE THREAD

**Issue by edulanasca** [Quantum3-Labs/scaffold-stark-2#144]
## Issue Overview

- In branch `v2-structs`
- Remember to update to scarb 2.6.4

Currently the arrow shows like this
<img width="830" alt="image" src="https://github.com/Quantum3-Labs/scaffold-stark-2/assets/43045722/afc2cc5b-21b6-460f-a66f-9e01e0644dbf">

It should be like this
<img width="880" alt="image" src="https://github.com/Quantum3-Labs/scaffold-stark-2/assets/43045722/b9c4bdb3-44e2-4a3a-bdf3-a87e01b714bc">

## Proposed Solutions or Ideas

Outline your proposed solution or share any ideas you have for discussing or resolving the issue.

**Comment by Jemiiah** [comment]
I’d love to work on more issues when they drop
