### ISSUE TITLE
Add Devcontainer

### ISSUE THREAD

**Issue by tensojka** [Quantum3-Labs/scaffold-stark-2#151]
## Issue Overview

It would be nice to have a devcontainer to install dependencies faster and fix snforge and scarb versions

## Proposed Solutions or Ideas

Copy and adjust the devcontainer from Konoha: https://github.com/CarmineOptions/konoha/tree/master/.devcontainer

Perhaps start from a node.js image, not Rust as we do, perhaps use a full Dockerfile.

**Comment by EjembiEmmanuel** [comment]
@tensojka I'd love to work on this

**Comment by tensojka** [comment]
@EjembiEmmanuel This is not my project:)

**Comment by EjembiEmmanuel** [comment]
Okay. @0xquantum3labs I'd love to work on this

**Comment by 0xquantum3labs** [comment]
closing this issue for now.
