### ISSUE TITLE
Correctly display available wallet connectors

### ISSUE THREAD

**Issue by 0xquantum3labs** [Quantum3-Labs/scaffold-stark-2#156]
## Issue Overview

Currently burner wallet connector can be used only on `devnet`, however when connected on sepolia or mainnet, it  still shows up. 
<img width="733" alt="image" src="https://github.com/Quantum3-Labs/scaffold-stark-2/assets/157618676/87f69639-0a31-409e-8e3d-bb0b54a1ddb9">
likewise, block burner wallet connector from 
## Proposed Solutions or Ideas

Move connectors out of [`ScaffoldStarkAppWithProviders`](https://github.com/Quantum3-Labs/scaffold-stark-2/blob/bb59cf4e0cfe0b4881104368288a1b5447224787/packages/nextjs/components/ScaffoldStarkAppWithProviders.tsx#L49C1-L52C6) to `~~/services/web3/connectors` , and filter connectors using the corresponding target network that is fetched from [`scaffold.config.ts`](https://github.com/Quantum3-Labs/scaffold-stark-2/blob/bb59cf4e0cfe0b4881104368288a1b5447224787/packages/nextjs/scaffold.config.ts#L12)

### Instructions for Contributing

- Leave a comment on this Issue.
- Wait for our confirmation to start on the project.
- Once you have received confirmation, begin working on your contribution.

### Incentives

Contributions are incentivized via Only Dust.

### Contact

For questions, join to our [tg group](https://t.me/+wO3PtlRAreo4MDI9) and reach out our team

**Comment by 0xquantum3labs** [comment]
sure

**Comment by gianalarcon** [comment]
@kenkomu are you still available to try this one? To assign to you

**Comment by kenkomu** [comment]
@gianalarcon yes I am still available I can attempt it.

**Comment by gianalarcon** [comment]
Do you have any update on this? @kenkomu

**Comment by kenkomu** [comment]
I am still working on it I will make a pull request very soon.

**Comment by danielcdz** [comment]
Hello! @0xquantum3labs I would love to help with this if possible, I'm an active OD contributor here is my profile: https://app.onlydust.com/u/danielcdz

**Comment by gianalarcon** [comment]
All yours @danielcdz! Any question please reach out our team

**Comment by danielcdz** [comment]
Got it, thank you! @gianalarcon

**Comment by danielcdz** [comment]
@gianalarcon I created this [PR](https://github.com/Quantum3-Labs/scaffold-stark-2/pull/189) that solves this issue, I'm open to receiving any feedback!
