### ISSUE TITLE
Write/Read support for structs & enums

### ISSUE THREAD

**Issue by edulanasca** [Quantum3-Labs/scaffold-stark-2#159]
## Issue Overview

Currently the debug doesn't support structs and enums.

## Proposed Solutions or Ideas

- Implementation of parser for structs and enums

**Comment by edulanasca** [comment]
Supported types. Last update 18/07/24

| Type            | Devnet | Sepolia - Braavos | Sepolia - Argent |
|-----------------|--------|-----------------|-------------------|
| felt252         | ✓      |   ✓         |       ✓            |
| u64             | ✓      |     ✓        |         ✓       |
| u256            | ✓      |     ✓      |                   |
| bool            | ✓      |       ✓     |         ✓      |
| tuple           | ✓      |    ✓         |                   |
| Contract Address| ✓      |    ✓      |        ✓      |
| Array  Basic Type*  | ✓      |      ✓       |      ✓      |
| Array Complex Type*     | ✓      |        ✓    |                   |
| Span Basic Type*     | ✓      |       ✓     |        ✓        |
| Span Complex Type*      | ✓      |       ✓     |             |
| ByteArray       | ✓    |       ✓      |      ✓          |
| Structs         | ✓      |      ✓        |                   |
| Enum            | ✓      |             |                   |
| Option          | ✓      |             |                   |
| Nested Struct | ✓ |    |  |

*Basic Type: u64, felt252
*Complex Type: u256, ByteArray

**Comment by metalboyrick** [comment]
as of 28 July 2024

| Type            | Devnet | Sepolia - Braavos | Sepolia - Argent |
|-----------------|--------|-----------------|-------------------|
| felt252         | ✓      |   ✓         |       ✓            |
| u64             | ✓      |     ✓        |         ✓       |
| u256            | ✓      |     ✓      |        ✓           |
| bool            | ✓      |       ✓     |         ✓      |
| tuple           | ✓      |    ✓         |          ✓         |
| Contract Address| ✓      |    ✓      |        ✓      |
| Array  Basic Type*  | ✓      |      ✓       |      ✓      |
| Array Complex Type*     | ✓      |        ✓    |       ✓             |
| Span Basic Type*     | ✓      |       ✓     |        ✓        |
| Span Complex Type*      | ✓      |       ✓     |     ✓         |
| ByteArray       | ✓    |       ✓      |      ✓          |
| Structs         | ✓      |      ✓        |         ✓            |
| Enum            | ✓      |        ✓       |         ✓           |
| Option          | ✓      |             |                   |
| Nested Struct | ✓ |  ✓   |  ✓    |
