### ISSUE TITLE
Allow switching accounts from connect modal when on Devnet

### ISSUE THREAD

**Issue by 0xquantum3labs** [Quantum3-Labs/scaffold-stark-2#163]
## Issue Overview

Currently when in Sepolia or Mainnet, it is sufficient to switch the account on the extension wallet we are connected to. 
However when being on devnet there is a need to disconnect and connect again to be able to choose a different wallet from the ones provided by devnet. 

<img width="724" alt="image" src="https://github.com/Quantum3-Labs/scaffold-stark-2/assets/157618676/1aa98df8-6d6c-45c3-9f09-ee29f594ef83">

 we should be able to switch wallets from here 

<img width="347" alt="image" src="https://github.com/Quantum3-Labs/scaffold-stark-2/assets/157618676/f7504747-4e9f-4cc6-96aa-85a2041aafcb">

### Only in devnet
Implement a `switch` functionality above the `disconnect`, replacing the `view on blockexplorer`. can either be a pop up or a toggle that shows me the other available wallets i can connect to

### Instructions for Contributing

- Leave a comment on this Issue.
- Wait for our confirmation to start on the project.
- Once you have received confirmation, begin working on your contribution.

### Incentives

Contributions are incentivized via Only Dust.

### Contact

For questions, join to our [tg group](https://t.me/+wO3PtlRAreo4MDI9) and reach out to @jrcarlos2000 and @EduJL

**Comment by egeaybars123** [comment]
Can I work on this issue @jrcarlos2000 @edulanasca?

**Comment by raizo07** [comment]
Hello @gianalarcon @0xquantum3labs   @edulanasca @jrcarlos2000 and @edujl

Can I be assigned to work on this issue. Will deliver a PR in ASAP.

**Comment by Gift-Naomi** [comment]
@gianalarcon @0xquantum3labs 
I would like to work on this issue. It seems that the devnet requires a full disconnect and reconnect to switch wallets, whereas Sepolia and Mainnet only require an account switch. My plan is to Implement a switch functionality above the disconnect button, showing a pop-up or toggle with available wallets to connect to, avoiding the need to disconnect and reconnect.

Please let me know if I can proceed with this.

**Comment by gianalarcon** [comment]
Go for it @egeaybars123. For questions, join to our [tg group](https://t.me/+wO3PtlRAreo4MDI9) and reach out to our team
