### ISSUE TITLE
Enhance Logging for Non deployed StarkNet Wallet in deploy.ts

### ISSUE THREAD

**Issue by edulanasca** [Quantum3-Labs/scaffold-stark-2#176]
## Issue Overview

Users currently face challenges during the deployment process when attempting to deploy a contract using an uninitialized StarkNet wallet. The deploy.ts script is responsible for this operation, fails silently without adequate feedback in the UI. 
This absence of clear messaging in the UI can lead to confusion and hinder effective troubleshooting. Addressing this issue by providing explicit UI alerts when the wallet is not yet deployed will significantly enhance user experience and guide them through the necessary pre-deployment steps.

## Proposed Solutions or Ideas

Implement additional logging within the deploy.ts script to check and report if the StarkNet wallet account has not been deployed. The script should include:

- A pre-deployment check to verify the existence and readiness of the StarkNet wallet account.
- Clear error messaging that specifically states the StarkNet wallet account needs to be initialized or deployed before proceeding with contract deployment.
- Guidance on steps to initialize or deploy the StarkNet wallet if it has not been done.

### Instructions for Contributing

- Leave a comment on this Issue.
- Wait for our confirmation to start on the project.
- Once you have received confirmation, begin working on your contribution.

### Incentives

Contributions are rewarded via Only Dust.

### Contact

For questions, join to our [tg group](https://t.me/+wO3PtlRAreo4MDI9) and reach out team

**Comment by raizo07** [comment]
@edulanasca can I be assigned to work on this?

**Comment by gianalarcon** [comment]
All yours @raizo07
