### ISSUE TITLE
Update ss2 docs

### ISSUE THREAD

**Issue by 0xquantum3labs** [Quantum3-Labs/scaffold-stark-2#211]
## Issue Overview

Based on latest [release](https://github.com/Quantum3-Labs/scaffold-stark-2/releases) udpate docs in [Scaffold-stark-docs](https://github.com/Quantum3-Labs/ss2-docs)

## Proposed Solutions or Ideas

- check new features and update docs

**Comment by Iwueseiter** [comment]
hi can i work on this

**Comment by EmmanuelAR** [comment]
Hey can I work on this ?

**Comment by josephchimebuka** [comment]
I would like to handle this

**Comment by Gift-Naomi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am a web3 developer and also a technical writer, Can i please work on  this issue?

### How I plan on tackling this issue
I will write a documentation that will meet the requirement and description of the issue.

**Comment by Nadai2010** [comment]
Hi everyone, @EmmanuelAR, @Gift-Naomi, @Iwueseiter and @josephchimebuka  we are preparing the issues for tomorrow's OD Hach, they will be assigned tomorrow

Remember that you can only work on one issue at a time, choose well

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello can I be assigned this please? I am a frontend developer and I'm also good at documentations. Below are some of the documentations I've done that were merged: https://github.com/keep-starknet-strange/joyboy/pull/143#event-13034455918 https://github.com/horuslabsio/Starknet-Scaffold/pull/94#event-13007360671 https://t.co/ZgK0ccPZpw https://t.co/GnBqVQPECz Here is my OnlyDust profile https://app.onlydust.com/u/od-hunter

### How I plan on tackling this issue
I will check for new features from the links provided and update the docs. I will send a PR within 2 days once I am assigned. I’m available to work please.

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
As an experienced analyst and blockchain developer with 15 years in the industry. i  likely encountered a variety of challenges that these technologies can help address. My technical expertise and problem-solving skills will be valuable assets in leveraging JavaScript, Cairo, and TypeScript.

### How I plan on tackling this issue
Review Latest Release
Identify new features, changes, and updates in the latest Scaffold-Stark release.
Update Documentation
Locate relevant sections in the Scaffold-Stark-Docs repo.
Update docs to reflect new features and changes.
Ensure clarity, conciseness, and ease of understanding.
Improve Existing Docs
Review overall structure and organization.
Enhance any unclear or lacking sections.
Code Examples
Update code snippets to match latest version.
Ensure examples are accurate and up-to-date.
Formatting and Styling
Maintain consistent formatting and styling.
Follow established guidelines in the docs repo.
Test and Review
Thoroughly test the updated documentation.
Consider peer review to catch any issues.
Commit and Push Changes
Commit updates to the docs repo.
Push changes to the main or release branch.

**Comment by 0xquantum3labs** [comment]
moving this to [docs](https://github.com/Quantum3-Labs/ss2-docs/issues)
