### ISSUE TITLE
Add class hash on debug page

### ISSUE THREAD

**Issue by 0xquantum3labs** [Quantum3-Labs/scaffold-stark-2#213]
## Issue Overview

Display class hash on `/debug` contracts

- below the address as a secondary label.
- should be able to copy to clipboard like the address component
- should be clickable and send to starkscan

this basically should follow a similar functionality to the address component but should be smaller below it as secondary

## Proposed Solutions or Ideas

- if needed update the `packages/snfoundry/deploy-contract.ts` script
- follow the current design / layout / colors

**Comment by EmmanuelAR** [comment]
Hey can work on this ?

**Comment by Jemiiah** [comment]
Hello @0xquantum3labs i would love to work on this issue 🚀

**Comment by Nadai2010** [comment]
Hi everyone, @EmmanuelAR and @Jemiiah  we are preparing the issues for tomorrow's OD Hach, they will be assigned tomorrow

Remember that you can only work on one issue at a time, choose well

**Comment by Jemiiah** [comment]
Thanks for the feedback @Nadai2010 would love to work on this when it start to get assigned tomorrow

**Comment by EmmanuelAR** [comment]
Thks for the opportunity, will be a pleasure @Nadai2010

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello, Please I will like to be assigned this issue. This is my first time applying in this ecosystem and I’d love to be given the opportunity. I am a full-stack blockchain Developer, and my experience includes html, css, react, JavaScript,TypeScript and Cairo.

### How I plan on tackling this issue
To solve this issue, I'll take the following steps:
1. I'll update the Frontend Component (the address Component: find where the address is displayed on the /debug contracts page, update this component to include the class hash below the address.
2. I'll make sure the class hash is being fetched and passed to the frontend.
3. I'll fetch Data on Frontend. While doing this I'll make sure to follow Design and Color Guidelines
4. Lastly, I'll test to see whether all changes have been successfully implemented.
I'll come with a PR within 5 days once I'm assigned.  Here is my Onlydust profile link https://app.onlydust.com/u/od-hunter. Please give me the opportunity.

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
As an experienced analyst and blockchain developer with 15 years in the industry. i  likely encountered a variety of challenges that these technologies can help address. My technical expertise and problem-solving skills will be valuable assets in leveraging JavaScript, Cairo, and TypeScript.

### How I plan on tackling this issue
Fetch Class Hash
Update deploy-contract.ts to retrieve class hash along with contract address.
Display Class Hash
Add class hash display below contract address on /debug page.
Include "Copy to clipboard" and "View on Starkscan" functionality.
Style Updates
Adjust CSS to make class hash display smaller and position it below the contract address.
Ensure layout and colors match existing design.
The key points are:

**Comment by ShantelPeters** [comment]
Hey can I work on this ? 

_Background and Leverage:_
As a frontend developer with experience in building interactive UI components and API integrations, I'm confident in my ability to tackle this challenge. My background in UI/UX design and development has equipped me with the skills to create intuitive and visually appealing interfaces. I'm well-versed in React and JavaScript, having worked on multiple projects that utilize these technologies.

_Approach to the Problem:_

1. _Update deploy-contract.ts script:_ I'll modify the packages/snfoundry/deploy-contract.ts script to include the class hash display functionality.
2. _Display Class Hash:_ I'll add a secondary label below the address on the /debug contracts page to display the class hash.
3. _Copy to Clipboard:_ I'll implement a copy-to-clipboard feature for the class hash, similar to the address component.
4. _Clickable and StarkScan Integration:_ I'll make the class hash label clickable, sending users to StarkScan when clicked.
5. _Design and Layout:_ I'll ensure the design and layout follow the existing guidelines, maintaining a consistent user experience.

_Solution:_
My proposed solution involves updating the deploy-contract.ts script and adding a secondary label to display the class hash. The label will be clickable, sending users to StarkScan, and will have a copy-to-clipboard feature.

_Technical Details:_

- I'll use React and JavaScript to implement the changes.
- I'll utilize the existing design system and components to maintain consistency.
- I'll ensure the class hash label is smaller and secondary to the address component.

**Comment by Nadai2010** [comment]
Hi @Jemiiah, we remind you that you must upload your PR or comments in order to continue with the assigned issue.

**Comment by Jemiiah** [comment]
I would create a PR soon @Nadai2010

**Comment by Nadai2010** [comment]
Thank you very much @Jemiiah
