### ISSUE TITLE
Create a Sample UI for YourContract | Hooks demo

### ISSUE THREAD

**Issue by 0xquantum3labs** [Quantum3-Labs/scaffold-stark-2#215]
## Issue Overview

- create a sample UI that showcases the usage of Scaffold custom hooks. this should be interactive and work on devnet and sepolia.
 - PR should be opened to [`hooks-example`](https://github.com/Quantum3-Labs/scaffold-stark-2/tree/hooks-example) branch
- integrate as many hooks as possible while keeping the flow understandable.

## Proposed Solutions or Ideas

- should follow layout / design / colors
- this should replace the example UI /home view.
- propose a written detail description of how this would work first

**Comment by josephchimebuka** [comment]
I like to handle this

**Comment by Gift-Naomi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am web3 developer

### How I plan on tackling this issue
i will meet all the requirement

**Comment by Nadai2010** [comment]
Hi everyone, @josephchimebuka and @Gift-Naomi we are preparing the issues for tomorrow's OD Hach, they will be assigned tomorrow

Remember that you can only work on one issue at a time, choose well

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hi , Please can I be assigned this issue? This is my first time applying in this ecosystem and I’d love to be given the opportunity. I am a full-stack blockchain Developer, and my experience includes html, css, react, JavaScript,TypeScript and Cairo.

### How I plan on tackling this issue
 To solve this issue, I'll take the following steps below:
!. I'd have to understand the requirements. I'll create a sample UI showcasing the usage of Scaffold custom hooks that should work on devnet and Sepolia. I'll open a PR to the hooks-example branch. I'll integrate as many hooks as possible while maintaining an understandable flow. I'll make sure to follow layout, design, and color guidelines. 
2. I'll plan the UI Layout(display a navigation bar with links to different parts of the sample UI, also a section to demonstrate each hook interactively(and every other thing that is needed).
3. I'll follow the color scheme. I'll use consistent fonts and sizes as per the design guidelines. I'll ensure the layout is responsive and user-friendly.
4. Next, I'll identify the hooks to be integrated (e.g., useState, useEffect, useContext, custom hooks like useFetch, useAuth, etc.). I'll plan how each hook will be demonstrated interactively.
5. I'll create all the Components needed(header,sidebar, footer etc)
6. Then, I'll implement and test each hook example(ensure they work on devnet and Sepolia by configuring the environments as needed).

Here is my Onlydust profile link https://app.onlydust.com/u/od-hunter. Please give me the opportunity. I’ll be able to come up with a PR within 3-5 working days.

**Comment by Calebux** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I'm very good at ui design and also double as a front end dev

### How I plan on tackling this issue
1. Design the UI Layout
Interactive Components:
Forms, buttons, and real-time data displays.
2. Integrate Scaffold Custom Hooks
useScaffoldEvent:
Real-time event notifications.
useScaffoldContract:
Form for contract interactions (read/write).
useScaffoldProvider:
Display network status and switch networks.
useScaffoldWallet:
Connect/disconnect wallet UI and display wallet info.
useScaffoldTransaction:
Send transactions and display their status.
4. Testing and Deployment
Test Thoroughly:
Verify functionality on devnet and Sepolia.
Open PR:
Submit to hooks-example branch with detailed documentation and reviewer instructions.

**Comment by HumbertoTM10** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I have 4 years working in development environments, specifically with JavaScript and TypeScript mainly, so that gives me a better understanding of the code and how to solve problems efficiently.

### How I plan on tackling this issue
First off all, study thoroughly the desing patterns in order to make somwthing really aligned to the project. Then work in the hooks to allow function components to have access to state and other React features.

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
As an experienced analyst and blockchain developer with 15 years in the industry. i  likely encountered a variety of challenges that these technologies can help address. My technical expertise and problem-solving skills will be valuable assets in leveraging JavaScript, Cairo, and TypeScript.

### How I plan on tackling this issue
Set up the project
Develop the UI component
Integrate the component into the main app
Run the development server

**Comment by ShantelPeters** [comment]
I am applying to this issues via a [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark)
*Background and Leverage:*
As a frontend developer with [3] years of experience in building interactive and responsive UI components, I'm confident in my ability to tackle this challenge. My background in UI/UX design and development has equipped me with the skills to create intuitive and visually appealing interfaces. I'm well-versed in React and custom hooks, having worked on multiple projects that utilize these technologies.

*Approach to the Problem:*

1. *Research and Planning:* I'll start by researching existing Scaffold custom hooks and their use cases to understand the requirements and possibilities.
2. *Design and Prototyping:* I'll create a written description and visual mockups of the proposed UI, ensuring it meets the layout, design, and color requirements.
3. *Development:* I'll develop the interactive UI sample, integrating multiple custom hooks while maintaining a clear and understandable flow.
4. *Testing and Iteration:* I'll test the UI on devnet and sepolia, iterating on the design and functionality based on feedback and results.
5. *PR and Documentation:* I'll open a PR to the hooks-example branch, including detailed documentation on the implemented solution and how it works.

*Proposed Solution:*
My proposed solution will involve creating a modular, reusable UI component that showcases the power of Scaffold custom hooks. I'll focus on creating an intuitive flow, demonstrating how multiple hooks can work together seamlessly. The design will follow the specified layout, design, and color guidelines, replacing the existing example UI/home

**Comment by lauchaves** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hey! I'm Lau Chaves, and I would like to contribute to this issue!

I have over 5 years of experience working with JavaScript, React, and TypeScript, ruby... I have some experience working and testing between networks, having contributed to another project using Sepolia and Mainnet. 

My primary role has been as a front-end developer, and I have a keen eye for detail and a strong focus on mobile-first approaches. I ensure the quality of my work through rigorous QA processes. Additionally, I'm proficient in working with design tools like Figma and Zeplin to follow designs meticulously. I have a solid knowledge of CSS, Sass, and styled-components. 

Feel free to check my onlydust profile here and github profile: lauchaves! 

### How I plan on tackling this issue
- Review Specifications:

Thoroughly review the project specifications and requirements.
Clarify any ambiguities with the project leads or other involved parties.

- Double-Check Contract Section:

Ensure that every aspect required to be shown in "your contract" section is available and correctly implemented.

- UI Development:

Create branch based on `hooks-example` 
Develop the new example UI based on the provided specifications.
Replace the current example UI in the /home view with the new design.
Integrate the Scaffold custom hooks in a way that is both comprehensive and easy to understand.

Design Consistency:

Follow the layout, design, and color guidelines to maintain consistency.
Use the design tool provided to ensure the design is accurately implemented.

Testing and Validation:

Test the new UI on both devnet and Sepolia to ensure compatibility and functionality.
Perform thorough self-QA to identify and resolve any issues.

By leveraging my background and expertise, I am confident in delivering a high-quality, interactive UI that effectively showcases the usage of Scaffold custom hooks, I’ll be able to come up with a PR within 3-5 working days!

**Comment by melnikga** [comment]
I can take this

**Comment by Nadai2010** [comment]
Hi @melnikga, we remind you that you must upload your PR or comments in order to continue with the assigned issue.

**Comment by melnikga** [comment]
@Nadai2010 Hi, today I will add the first PR

**Comment by Nadai2010** [comment]
Thank you very much @melnikga

**Comment by 0xquantum3labs** [comment]
Hi @melnikga , any updates on this PR ?

**Comment by melnikga** [comment]
@0xquantum3labs Hey, there were some difficulties due to the fact that I work on windows, I am currently working on their solution, I'm sorry for the delay

**Comment by melnikga** [comment]
@0xquantum3labs
Hey, I created a PR, please read the commit, maybe I didn't fully understand what exactly needed to be done
