### ISSUE TITLE
migration v3

### ISSUE THREAD

**Issue by 0xquantum3labs** [Quantum3-Labs/scaffold-stark-2#216]
## Issue Overview

The idea is to migrate the stack to support [`starknet-react:next`  ](https://starknet-react-website.vercel.app/docs/getting-started) 
- should support RPC v0.7.1
- should support `next` version of starknet react
- should support deployment and usage of extension wallets on devnet
- should support `starknet-js:^6.11.0`

## Proposed Solutions or Ideas

- update workflows
- update `snfoundry` package where needed

**Comment by EjembiEmmanuel** [comment]
@0xquantum3labs I'd love to work on this

**Comment by metalboyrick** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Experienced full stack developer with scaffold stark 2 contribution experience
