### ISSUE TITLE
Improve `deploy` function on `deploy-contract.ts`

### ISSUE THREAD

**Issue by 0xquantum3labs** [Quantum3-Labs/scaffold-stark-2#217]
## Issue Overview

- update the order of functions, able to receive null constructor params
- the only `required` param is the contractName.
- receives the contract name first, then optional `exportContractName`, then the optional`constructor params`,  and finally the `options`
- makes good usage of  `options` and `maxFee`
- remove unused imports
- good error logging for all cases !
- other dev improvements ++

## Proposed Solutions or Ideas

- should be tested on all networks.

**Comment by adrianvrj** [comment]
Hi, can I work on this on tomorrow's odhack if I don't get any other issues assigned?

**Comment by ikemHood** [comment]
Hey @0xquantum3labs  can i take on this?

**Comment by Nadai2010** [comment]
Hi everyone, @adrianvrj and @ikemHood we are preparing the issues for tomorrow's OD Hach, they will be assigned tomorrow

Remember that you can only work on one issue at a time, choose well

**Comment by BernalHQ** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello, my name is Bernal. I am a software developer from Costa Rica. Currently, I work as a back-end developer. In my previous job, I worked as a full-stack developer. Personally, I enjoy developing both the back end and the front end. I have 4 years of experience in the software development industry. Some technologies I have worked with include: Typescript, React, C#, and Node.


### How I plan on tackling this issue
To reach the solution, the first step is to understand how the project works. This involves familiarizing yourself with the project's documentation, structure, and codebase. Next, thoroughly review the issue description to grasp the problem fully. Based on this understanding, brainstorm and propose a viable solution. Once you have a clear plan, implement the solution in the code. After coding, conduct comprehensive tests to ensure the fix resolves the issue without introducing new problems. Finally, review your changes and prepare them for submission, ensuring all aspects of the issue have been addressed effectively.

**Comment by oceanlvr** [comment]
> - good error logging for all cases !

maybe something tool like Chalk is good.


> update the order of functions, able to receive null constructor params

do you mean make it null by default.
<img width="458" alt="image" src="https://github.com/user-attachments/assets/064dd9df-7ab5-44e3-ad01-7ae510cc8af4">

- makes good usage of options and maxFee
The implications here may need to be discussed

**Comment by renzobanegass** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hi! I'm Renzo, a Software Engineer with over 5+ years of experience, I recently joined Dojo Coding to start contributing to Web3 OSS. This would be one of my first contributions! I have worked with C#, Java, Kotlin and Typescript in the past.

### How I plan on tackling this issue
**Understand Requirements:**

- Reorder parameters: 'contractName' (required), then optional 'exportContractName', 'constructorParams', and 'options'.
- Ensure null handling for optional parameters.
- Optimize usage of options and maxFee.
- Remove unused imports and enhance error logging.

**Review Closed PR:**

- Analyze the changes and feedback in PR #220 to identify pitfalls and improvement areas.

**Implement Changes:**

- Modify deployContract function as per requirements.
- Implement comprehensive error handling and logging.
- Clean up unused imports.

**Testing:**

- Validate changes on all networks to ensure compatibility and functionality.

**Submit PR:**

- Ensure thorough documentation and clear commit messages.

**Comment by ikemHood** [comment]
I am still working on this, would create a new PR shortly.
