### ISSUE TITLE
Documentation regarding UI libraries

### ISSUE THREAD

**Issue by metalboyrick** [Quantum3-Labs/scaffold-stark-2#218]
## Issue Overview

Suggestions are being made to better support other UI libraries. This should be updated on [this repo](https://github.com/Quantum3-Labs/ss2-docs)

## Proposed Solutions or Ideas

Current implementation only makes use of DaisyUI and low level vanilla implementations. This should provide flexibility to install any UI libraries people may want to use. Documentations or FAQ entries can be written to address the question

**Comment by EmmanuelAR** [comment]
Hey can I take this ?

**Comment by raizo07** [comment]
@metalboyrick Hello I'll like to work on this

**Comment by Joy-Adah** [comment]
Hi @metalboyrick I'll love to work on this. Kindly assign 🚀

**Comment by 0xquantum3labs** [comment]
moving this to [docs](https://github.com/Quantum3-Labs/ss2-docs/issues)
