### ISSUE TITLE
Setting BlockExplorer to Chains and integrate into footer

### ISSUE THREAD

**Issue by Nadai2010** [Quantum3-Labs/scaffold-stark-2#224]
## Issue Overview

Remove BlockExplore in Devnet and add it in Sepolia and Mainnet, should maintain the elegant design and code of this issue #214 and offer various explorer options.

**Something like this**

![EXPLORER](https://github.com/user-attachments/assets/3511f1ca-0991-4b7a-b579-f804eb4469c4)

- Footer Devnet: 
  - Price 
  - Faucet
- Footer Sepolia:
  - Price 
  - FaucetSepolia
  - Explorer Sepolia (Various options)
- Footer Mainnet:
   - Price
   - Explorer Mainnet (Varios options)

The 3 browser options we can use will need to detect Sepolia or Mainnet and the browser links will also be different:

Mainnet
- [Starkscan](https://starkscan.co/)
- [Voyager](https://voyager.online/)
- [StarkCompass](https://starkcompass.com/)

Sepolia
- [Starkscan Sepolia](https://sepolia.starkscan.co/)
- [Voyager Sepolia](https://sepolia.voyager.online/)
- [StarkCompass](https://starkcompass.com/sepolia/)
- 
## Proposed Solutions or Ideas

- Create BlockExplorer with a button with similar functions to faucet.
- When on sepolia or mainnent, shows a list of links for users to click and redirect to external websites that have Block Explorer

**Comment by Iwueseiter** [comment]
Hi @Nadai2010 can I work on this?

**Comment by Calebux** [comment]
Hi @Nadai2010 I can take this up and deliver

**Comment by Ayoazeez26** [comment]
Hi @Nadai2010 I'd like to work on this?
