### ISSUE TITLE
Improve ABIs and predeployed contracts

### ISSUE THREAD

**Issue by jrcarlos2000** [Quantum3-Labs/scaffold-stark-2#237]
## Issue Overview

create a `constants.ts` file that stores the addresses & classhash of `Eth`, `Strk`, and one single `ERC20 ABI`. we should be able to use these inside `predeployedContracts.ts` 

all these values are constant and are the same regardless of the network.

also add support of `Strk`, `Eth` on mainnet.

## Proposed Solutions or Ideas

currently ABI in devnet doesnt match ABI on sepolia, due to a previous mismatch between devnet and public networks. But now this should be solved. use ONE single ABI for all tokens.

**Comment by adrianvrj** [comment]
Hey, can I work on this?

**Comment by raizo07** [comment]
Hello @jrcarlos2000 can I work on this? 

I just worked on something similar.

**Comment by martinvibes** [comment]
hi @jrcarlos2000 i would love to work on this issue and i will also love to be a contributor to your repo
 @jrcarlos2000

**Comment by Ayoazeez26** [comment]
Hi @jrcarlos2000 I would love to work on this

**Comment by lauchaves** [comment]
Hey! I'm Lau Chaves, is this still open for contribution? If so I would like to contribute to this issue!

Feel free to check my [onlydust profile ](https://app.onlydust.com/u/lauchaves)here and github profile: [lauchaves](https://github.com/lauchaves)!

**Comment by od-hunter** [comment]
Hi @0xquantum3labs ,is this open for contribution? If yes, can I work on this please?
