### ISSUE TITLE
Bug | Improvement : useScaffoldContract hook

### ISSUE THREAD

**Issue by 0xquantum3labs** [Quantum3-Labs/scaffold-stark-2#243]
## Issue Overview

[IN PUBLIC NETWORK]

We declare a contract through the useScaffoldContract hook using an Account or publicClient. [here](https://github.com/Quantum3-Labs/scaffold-stark-2/blob/c436d25ce6356867950b78c9f0425b21eac2ae7f/packages/nextjs/hooks/scaffold-stark/useScaffoldContract.ts#L30-L31)

the following code:
```typescript
  const {data : Eth} = useScaffoldContract({
    contractName: "Eth"
  })

  const writeAsync = async () => {
    console.log(Eth?.providerOrAccount);
    const balance = await Eth?.functions["balanceOf"]("0");
  }
```

will fail when extension wallet is connected, when the Contract instance is initialized with Account.  
will succeed when wallet is not connected, when the Contract instance is initialized with Public Client.

the error is the following:
<img width="390" alt="image" src="https://github.com/user-attachments/assets/9eb16dbd-a60c-46c2-8e7d-77ce7363f048">

## Proposed Solutions or Ideas ( in order of priority )

- Bug on useAccount() which gives a wrong form of Provider inside the Account object ?
- Context of Starknet React not getting the right provider.
- `account || publicClient` -> `publicClient` [here](https://github.com/Quantum3-Labs/scaffold-stark-2/blob/c436d25ce6356867950b78c9f0425b21eac2ae7f/packages/nextjs/hooks/scaffold-stark/useScaffoldContract.ts#L30-L31)
   - this will lead to not being able to invoke functions using the connected account. it will be a read only.
- create a tag for read only and use Account or either publicClient to initialize the contract instance

**Comment by metalboyrick** [comment]
Triage findings: works with reads but not writes

used the following code to verify
```typescript
 const writeAsync = async () => {
    console.log({ providerOrAccount: Eth?.providerOrAccount });

    const providerOrAccount = Eth?.providerOrAccount;

    try {
      // sample write
      const callResultRead = await providerOrAccount?.callContract({
        contractAddress: Eth?.address as string,
        calldata: [
          "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d",
          "0x29d394a5d6305440000",
          "0x0",
        ],
        entrypoint: "approve",
      });

      // sample read
      const callResultWrite = await providerOrAccount?.callContract({
        contractAddress: Eth?.address as string,
        calldata: [
          "0x000a347aa8e1B4CA547da97047204a23f44F713Ec0A463270D994e9a97EC3af6",
        ],
        entrypoint: "balanceOf",
      });

      console.debug({ callResultRead, callResultWrite });
    } catch (e) {
      console.error(e.stack);
    }
```

**Comment by metalboyrick** [comment]
Triage findings (2) Slightly different structure between Account instances of burner wallet and other wallets

```typescript
const burnerAccount = {
  responseParser: {},
  channel: {
    nodeUrl: "https://starknet-sepolia.public.blastapi.io",
    headers: {
      "Content-Type": "application/json",
    },
    retries: 200,
    requestId: 0,
    blockIdentifier: "pending",
    chainId: "0x534e5f5345504f4c4941",
    waitMode: false,
  },
  signer: {
    pk: "0xa20a02f0ac53692d144b20cb371a60d7",
  },
  address: "0x49dfb8ce986e21d354ac93ea65e6a11f639c1934ea253e5ff14ca62eca0f38e",
  transactionVersion: "0x2",
};

const argentAccount = {
  provider: {
    nodeUrl: "https://starknet-sepolia.public.blastapi.io",
    headers: {
      "Content-Type": "application/json",
    },
    responseParser: {},
    retries: 200,
    blockIdentifier: "pending",
    chainId: "0x534e5f5345504f4c4941",
    nodeUrls: [
      "https://starknet-sepolia.public.blastapi.io",
      "https://rpc.starknet-sepolia.lava.build",
    ],
    nodeIndex: 0,
    maxRetryCount: 5,
  },
  signer: {
    pk: "051052e1fc3b780e8df38758353cd89cef2c75a3f9ae6e4c3d82f966ab331a28",
  },
  address: "0x2d0e2c634d55149e62a092fc56c1ccb4e9604d6ebd716728c94a4f92c6e0e05",
};

const bravoosAccount = {
  provider: {
    responseParser: {},
    nodeUrl: "https://starknet-sepolia.public.blastapi.io",
    retries: 200,
    headers: {
      "Content-Type": "application/json",
    },
    blockIdentifier: "pending",
    chainId: "0x534e5f5345504f4c4941",
  },
  address: "0x2a5d8b9e5693481045403bed72f5feb5ecc822de8a98fc385fb4abae2dda1e2",
  signer: {
    pk: "0x0",
  },
};

```

**Comment by metalboyrick** [comment]
Notes (3) the `response.flat()` error happens in bravoos, argent has a different error. Stepping through the bravoos wallet when this error occurs indicate that this error happens in their parser due to the write error mentioned in (1)

**Comment by 0xquantum3labs** [comment]
> Notes (1) works with reads but not writes
> 
> used the following code to verify
> 
> ```ts
>  const writeAsync = async () => {
>     console.log({ providerOrAccount: Eth?.providerOrAccount });
> 
>     const providerOrAccount = Eth?.providerOrAccount;
> 
>     try {
>       // sample write
>       const callResultRead = await providerOrAccount?.callContract({
>         contractAddress: Eth?.address as string,
>         calldata: [
>           "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d",
>           "0x29d394a5d6305440000",
>           "0x0",
>         ],
>         entrypoint: "approve",
>       });
> 
>       // sample read
>       const callResultWrite = await providerOrAccount?.callContract({
>         contractAddress: Eth?.address as string,
>         calldata: [
>           "0x000a347aa8e1B4CA547da97047204a23f44F713Ec0A463270D994e9a97EC3af6",
>         ],
>         entrypoint: "balanceOf",
>       });
> 
>       console.debug({ callResultRead, callResultWrite });
>     } catch (e) {
>       console.error(e.stack);
>     }
> ```

Yes we need a signer in order to be able to `write`.
