### ISSUE TITLE
[Starknet-react] Missing useBalance property

### ISSUE THREAD

**Issue by edulanasca** [Quantum3-Labs/scaffold-stark-2#59]
## Issue Overview

blockTag | blockIdentifier following wagmi specs. we need to be able to use the hook `useBalance()`  as in here [https://github.com/Quantum3-Labs/scaffold-stark-2/blob/bf3aea74501c1c2d08d7b38695f[…]packages/nextjs/hooks/scaffold-stark/useScaffoldContractRead.ts](https://github.com/Quantum3-Labs/scaffold-stark-2/blob/bf3aea74501c1c2d08d7b38695f55887d5134bab/packages/nextjs/hooks/scaffold-stark/useScaffoldContractRead.ts#L29C1-L37C47)

## Proposed Solutions or Ideas

Outline your proposed solution or share any ideas you have for discussing or resolving the issue.

**Comment by 0xquantum3labs** [comment]
@edulanasca  we can use the `useContractRead` function to read from the `ETH_CONTRACT`, we can read the function `balanceOf`. this is a custom implementation of the `useBalance` hook
