### ISSUE TITLE
Create select account with burner wallet

### ISSUE THREAD

**Issue by gianalarcon** [Quantum3-Labs/scaffold-stark-2#77]
## Issue Overview

Currently when we connect to burner wallet, it takes the first account from the staknet devnet list accounts.

## Proposed Solutions or Ideas

After we click on burner wallet, we should show a list of available starknet devnet accounts 
@jrcarlos2000 your feedback here

**Comment by 0xquantum3labs** [comment]
we should have a proper figma file for this

**Comment by edulanasca** [comment]
I think after select burner wallet, it should display another modal (or in the same modal) the list of burner wallets.
To make this possible, we'd have to change a lot of components starting with `ConnectModal` `ScaffoldStarkAppWithProviders` as the Burner is a custom implementation of `InjectedConnector`
maybe `new BurnerConnector()` can accept the index of the wallet selected and then fetch that wallet 

<img width="724" alt="image" src="https://github.com/Quantum3-Labs/scaffold-stark-2/assets/43045722/02e5b264-3bb0-44c9-aea0-b6170b977ab3">
